
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS'

export const SET_MEMBER_ACTIVITY_BY_TELEPHONE = 'SET_MEMBER_ACTIVITY_BY_TELEPHONE'

export const SET_LIST_COUPON_BY_STATUS = 'SET_LIST_COUPON_BY_STATUS'

export const SET_CITY_LIST = 'SET_CITY_LIST'

export const SET_SHOP_LIST = 'SET_SHOP_LIST'

export const RESET_SHOP_LIST = 'RESET_SHOP_LIST'


