export const SET_SETTING = 'SET_SETTING'
export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS'
export const FAMILY_SUCCESS = 'FAMILY_SUCCESS'
export const ARTICLE_SUCCESS = 'ARTICLE_SUCCESS'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
export const SET_FAMILY_LIST_TYPE = 'SET_FAMILY_LIST_TYPE'

export const SET_CART_ITEM = 'SET_CART_ITEM'
export const ADD_SHOP_CART = 'ADD_SHOP_CART'
export const CUT_SHOP_CART = 'CUT_SHOP_CART'
export const TOTAL_PRICE = 'TOTAL_PRICE'

export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE'
